# Generated by Django 5.2 on 2025-12-11 16:06

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "_id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "tags",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=models.CharField(max_length=20)
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", django_mongodb_backend.fields.ObjectIdField()),
            ],
        ),
    ]
