# Generated by Django 5.2 on 2025-12-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="analysis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
